# Generated by Django 4.1.5 on 2023-02-07 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('date', models.DateField(db_index=True)),
                ('town', models.CharField(max_length=50)),
                ('age', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='badm.age', verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=254)),
                ('lname', models.CharField(max_length=254)),
                ('registered', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата регистрации')),
                ('email', models.EmailField(max_length=254)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='badm.age', verbose_name='Возраст')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='badm.events', verbose_name='Мероприятие')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='badm.groups', verbose_name='Группа')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='badm.types', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['registered'],
            },
        ),
        migrations.AddField(
            model_name='events',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='badm.groups', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='events',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='badm.organizers', verbose_name='Организатор'),
        ),
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='badm.types', verbose_name='Тип'),
        ),
    ]
