# Generated by Django 4.1.5 on 2023-02-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='age',
            options={'ordering': ['value'], 'verbose_name': 'Возрастная категория', 'verbose_name_plural': 'Возрастные категории'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['value'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='organizers',
            options={'ordering': ['value'], 'verbose_name': 'Организатор', 'verbose_name_plural': 'Организаторы'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'ordering': ['value'], 'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.RemoveField(
            model_name='events',
            name='group',
        ),
        migrations.RemoveField(
            model_name='events',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='events',
            name='type',
        ),
        migrations.AddField(
            model_name='events',
            name='groups',
            field=models.ManyToManyField(to='badm.groups'),
        ),
        migrations.AddField(
            model_name='events',
            name='organizers',
            field=models.ManyToManyField(to='badm.organizers'),
        ),
        migrations.AddField(
            model_name='events',
            name='types',
            field=models.ManyToManyField(to='badm.types'),
        ),
        migrations.RemoveField(
            model_name='events',
            name='age',
        ),
        migrations.AddField(
            model_name='events',
            name='age',
            field=models.ManyToManyField(to='badm.age'),
        ),
    ]
