# Generated by Django 4.1.5 on 2023-02-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badm', '0002_alter_age_options_alter_groups_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='group',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='type',
        ),
        migrations.AddField(
            model_name='participants',
            name='groups',
            field=models.ManyToManyField(to='badm.groups'),
        ),
        migrations.AddField(
            model_name='participants',
            name='types',
            field=models.ManyToManyField(to='badm.types'),
        ),
        migrations.RemoveField(
            model_name='participants',
            name='age',
        ),
        migrations.AddField(
            model_name='participants',
            name='age',
            field=models.ManyToManyField(to='badm.age'),
        ),
    ]
